kind = "DojoModel"
class_hash = "0x666688f77c24d5fd9eb3e2c218946e7f6eadc8e00198863f8bf13015f2f867f"
original_class_hash = "0x666688f77c24d5fd9eb3e2c218946e7f6eadc8e00198863f8bf13015f2f867f"
abi = "manifests/dev/abis/base/models/dojo_starter_models_round_round.json"
name = "dojo_starter::models::round::round"

[[members]]
name = "duel_id"
type = "u128"
key = true

[[members]]
name = "round_number"
type = "u8"
key = true

[[members]]
name = "state"
type = "u8"
key = false

[[members]]
name = "move_a"
type = "Moves"
key = false

[[members]]
name = "move_b"
type = "Moves"
key = false
